-- Link pages: the first two pages, moved from linktr.ee on 2 October 2026. Seeds run once each (lp_seeds),
-- so later edits in the editor are never overwritten by a deploy.
-- Owner emails are placeholders (.invalid): set the real address from /admin/links/ ("Change email"), never in git.
CREATE TABLE IF NOT EXISTS lp_seeds (name TEXT PRIMARY KEY, at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')));

-- martin
INSERT OR IGNORE INTO lp_people (handle, email, name, bio, photo, kind, status) SELECT 'martin', 'martin@links.invalid', 'Martin Currie', 'Biochemical Engineer working on sustainable alternative protein for human consumption, open bioreactors and productivity software to enable the above.', '/link-media/martin-currie.jpg', 'person', 'active' WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'link', 'patreon', 'Patreon', 'https://patreon.com/AMYBO', 'patreon', 7, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'group-1', 'AMYBO - sustainable protein for all', 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-1'), 'link', 'amybo', 'AMYBO', 'https://amybo.org/', 'amybo', 6, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-1'), 'link', 'amybo-youtube', 'AMYBO YouTube', 'https://youtube.com/@amybo', 'youtube', 8, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-1'), 'link', 'amybo-links', 'More AMYBO links', 'https://linktr.ee/amybo.org', 'linktree', 3, 2 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'group-2', 'andeye - software & photography', 2 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-2'), 'link', 'andeye', 'andeye - productivity software', 'https://www.andeye.com/', 'software', 1, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-2'), 'link', 'andeye-photo', 'andeye Photography', 'https://andeye.photo/', 'camera', 5, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'group-3', 'Aqueum - water quality & treatment', 3 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-3'), 'link', 'aqueum', 'Aqueum', 'https://www.aqueum.com/', 'water', 6, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-3'), 'link', 'aqueum-cv', 'Aqueum CV', 'https://aqueum.com/people/martin-currie/', 'cv', 19, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'group-4', 'Stuff', 4 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-4'), 'link', 'music', 'Music to work to', 'https://ambi4.work/', 'music', 12, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-4'), 'link', 'wishlist', 'Wish list - stuff I''d like but haven''t yet got', 'https://gowish.com/s/dxn7bg', 'gift', 15, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'group-5', 'Socials', 5 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-5'), 'link', 'linkedin', 'LinkedIn', 'https://www.linkedin.com/in/martincurrie/', 'linkedin', 12, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-5'), 'link', 'x', 'X - rarely checked', 'https://twitter.com/martin_currie', 'x', 4, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-5'), 'link', 'mastodon', 'Mastodon - rarely checked', 'https://mas.to/@Aqueum', 'mastodon', 3, 2 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-5'), 'link', 'zotero', 'Zotero', 'https://www.zotero.org/martincurrie', 'zotero', 9, 3 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-5'), 'link', 'qrz', 'MM7MMU on QRZ.com', 'https://www.qrz.com/db/MM7MMU', 'radio', 4, 4 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'group-6', 'Email', 6 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'group-6'), 'link', 'email', 'Get in touch', 'https://contact.andeye.com/?source=amy.bo%2F~martin&subject=Message%20for%20Martin%20Currie', 'mail', 0, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-v1');
INSERT OR IGNORE INTO lp_seeds (name) VALUES ('martin-v1');

-- amybo
INSERT OR IGNORE INTO lp_people (handle, email, name, bio, photo, kind, status) SELECT 'amybo', 'hello@amybo.org', 'AMYBO', 'AMYBO is an open source protein fermentation community', '/link-media/amybo.svg', 'org', 'active' WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'waitlist', 'Join the free bioreactor waitlist', 'https://amybo.us17.list-manage.com/subscribe?u=6f309c6b041857567b9962872&id=c1cd11b645', 'mail', 0, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'forum', 'Ask questions in our forum', 'https://forum.amybo.org/', 'forum', 0, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'youtube', 'Learn more on YouTube', 'https://www.youtube.com/@amybo', 'youtube', 0, 2 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'website', 'Check out our website', 'https://amybo.org/', 'amybo', 0, 3 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'github', 'Contribute on GitHub', 'https://github.com/amy-bo', 'github', 0, 4 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'docs', 'Read our docs', 'https://amybo.org/docs', 'docs', 0, 5 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'prints', 'Print our stuff', 'https://www.printables.com/@AMYBO_2001380', 'print', 0, 6 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'link', 'contact', 'Contact us', 'https://contact.andeye.com/?source=amy.bo%2F~amybo&subject=Message%20from%20amy.bo&cb=Volunteering&cb=Running%20an%20experiment&cb=Building%20an%20electroPioreactor&cb=Funding%20or%20sponsorship&cb=Press%20or%20speaking&cb=Something%20else', 'mail', 0, 7 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), NULL, 'group', 'group-1', 'People', 8 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'amybo') AND slug = 'group-1'), 'link', 'martin', 'Martin', 'https://amy.bo/~martin', 'person', 0, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'amybo') AND slug = 'group-1'), 'link', 'martin-patreon', 'Martin''s Patreon', 'https://www.patreon.com/amybo', 'patreon', 0, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, seed, position) SELECT (SELECT id FROM lp_people WHERE handle = 'amybo'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'amybo') AND slug = 'group-1'), 'link', 'gerrit-margriet', 'Gerrit and Margriet', 'https://labcrafter.co.uk/pages/about-us', 'person', 0, 2 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'amybo-v1');
INSERT OR IGNORE INTO lp_seeds (name) VALUES ('amybo-v1');

