-- Link pages, 5 October 2026: Martin's page as he edited it in the local preview (before he could sign in to the
-- live editor): group pictures, colours, the diary and the Volunteer note. Replaces his items once; click counts are
-- kept, since they're stored by address and the links keep theirs. Uploaded pictures stay local (no bucket yet).
DELETE FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'amybo-sustainable-protein-for-all', 'AMYBO - sustainable protein for all', '', 'amybo-dark', '', '', 0, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'andeye-software-photography', 'andeye - software & photography', '', 'andeye', '', '', 1, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'aqueum-water-quality-treatment', 'Aqueum - water quality & treatment', '', 'aqueum', '', '', 2, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'stuff', 'Stuff', '', 'stuff', '', '', 3, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'socials', 'Socials', '', 'people', '', '', 4, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'group', 'help-me', 'Help me', '', 'star', '', '', 5, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), NULL, 'link', 'email', 'Email', 'https://contact.andeye.com/?source=amy.bo&heading=Contact%20Martin&subject=Message%20for%20Martin%20Currie', 'mail', '', '', 6, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'amybo-sustainable-protein-for-all'), 'link', 'amybo', 'AMYBO', 'https://amybo.org/', 'amybo', '', '', 0, 6 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT OR REPLACE INTO lp_node_dark (node_id, linked, icon, tint, zoom) SELECT id, 0, 'amybo-dark', 'mono', 1 FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'amybo' AND NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'amybo-sustainable-protein-for-all'), 'link', 'amybo-youtube', 'AMYBO YouTube', 'https://youtube.com/@amybo', 'youtube', '', '', 1, 8 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT OR REPLACE INTO lp_node_meta (node_id, tint, zoom, day, highlight) SELECT id, 'mono', 1, '', 0 FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'amybo-youtube' AND NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'amybo-sustainable-protein-for-all'), 'link', 'amybo-links', 'More AMYBO links', 'https://linktr.ee/amybo.org', 'link', '', '', 2, 3 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'amybo-sustainable-protein-for-all'), 'diary', 'diary', 'My AMYBO diary', '', 'diary', '', '', 3, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'andeye-software-photography'), 'link', 'andeye', 'andeye - productivity software', 'https://www.andeye.com/', 'andeye-inv', '', '', 0, 1 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'andeye-software-photography'), 'link', 'andeye-photo', 'andeye Photography', 'https://andeye.photo/', 'camera', '', '', 1, 5 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'aqueum-water-quality-treatment'), 'link', 'aqueum', 'Aqueum', 'https://www.aqueum.com/', 'aqueum-q', '', '', 0, 6 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'aqueum-water-quality-treatment'), 'link', 'aqueum-cv', 'Aqueum CV', 'https://aqueum.com/people/martin-currie/', 'cv', '', '', 1, 19 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'stuff'), 'link', 'music', 'Ambi4.work - generative browser synth', 'https://ambi4.work/', 'music', '', '', 0, 12 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT OR REPLACE INTO lp_node_meta (node_id, tint, zoom, day, highlight) SELECT id, '#ff932e', 1, '', 0 FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'music' AND NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'stuff'), 'link', 'wishlist', 'Wish list - stuff I''d like but haven''t yet got', 'https://gowish.com/s/dxn7bg', 'gift', '', '', 1, 15 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT OR REPLACE INTO lp_node_meta (node_id, tint, zoom, day, highlight) SELECT id, '#fbff00', 1, '', 0 FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'wishlist' AND NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'socials'), 'link', 'linkedin', 'LinkedIn', 'https://www.linkedin.com/in/martincurrie/', 'linkedin', '', '', 0, 12 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'socials'), 'link', 'x', 'X - rarely checked', 'https://twitter.com/martin_currie', 'x', '', '', 1, 4 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'socials'), 'link', 'mastodon', 'Mastodon - rarely checked', 'https://mas.to/@Aqueum', 'mastodon', '', '', 2, 3 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'socials'), 'link', 'zotero', 'Zotero', 'https://www.zotero.org/martincurrie', 'zotero', '', '', 3, 9 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'socials'), 'link', 'qrz', 'MM7MMU on QRZ.com', 'https://www.qrz.com/db/MM7MMU', 'radio', '', '', 4, 4 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'help-me'), 'link', 'patreon', 'Patreon', 'https://patreon.com/AMYBO', 'patreon', '', '', 0, 7 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'help-me'), 'text', 'volunteer', 'Volunteer', '', 'heart', '', 'If you''d like to help out with any of this pro bono please [email me](https://contact.andeye.com/?source=amy.bo&heading=Contact%20Martin&subject=Message%20for%20Martin%20Currie)', 1, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_nodes (person_id, parent_id, kind, slug, label, url, icon, image, body, position, seed) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), (SELECT id FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'diary'), 'text', 'amybo-website', 'AMYBO website', '', '', '', 'Currently diverted by this link-in-bio type system for volunteers and supporters...', 0, 0 WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT OR REPLACE INTO lp_node_meta (node_id, tint, zoom, day, highlight) SELECT id, '', 1, '261003', 0 FROM lp_nodes WHERE person_id = (SELECT id FROM lp_people WHERE handle = 'martin') AND slug = 'amybo-website' AND NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2');
INSERT INTO lp_page_meta (person_id, accent) SELECT (SELECT id FROM lp_people WHERE handle = 'martin'), '#6e11e6' WHERE NOT EXISTS (SELECT 1 FROM lp_seeds WHERE name = 'martin-page-v2') ON CONFLICT(person_id) DO UPDATE SET accent = excluded.accent;
INSERT OR IGNORE INTO lp_seeds (name) VALUES ('martin-page-v2');
