#!/usr/bin/env node
/**
 * Writes REVIEW.md: every page with its provenance (Amy / Hugo / new) and old Hugo URL, and checks that every
 * page of the old Hugo site has a counterpart in the built site (run `npm run build` first).
 *   npm run review
 */
import { readFileSync, readdirSync, statSync, existsSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = 'src/content/docs';
const walk = (d) => readdirSync(d).flatMap((f) => (statSync(join(d, f)).isDirectory() ? walk(join(d, f)) : [join(d, f)]));
const fm = (text) => {
	const m = /^---\n([\s\S]*?)\n---/.exec(text);
	const get = (k) => {
		const r = new RegExp(`^${k}:\\s*(.*)$`, 'm').exec(m?.[1] ?? '');
		return r ? r[1].replace(/^["']|["']$/g, '').trim() : '';
	};
	return { title: get('title'), source: get('source'), provenance: get('provenance'), hugoPath: get('hugoPath'), slug: get('slug') };
};
const urlFor = (file, slug) => {
	if (slug) return `/${slug}/`;
	let p = relative(ROOT, file).replace(/\.(md|mdx)$/, '').replace(/(^|\/)index$/, '');
	return `/${p ? `${p}/` : ''}`;
};
const esc = (s) => String(s).replace(/\|/g, '\\|');

const pages = walk(ROOT).filter((f) => /\.mdx?$/.test(f)).map((f) => ({ file: f, ...fm(readFileSync(f, 'utf8')) })).map((p) => ({ ...p, url: urlFor(p.file, p.slug) }));
pages.sort((a, b) => a.url.localeCompare(b.url));
const map = JSON.parse(readFileSync('migration/hugo-map.json', 'utf8'));
const built = (url) => existsSync(join('dist', url, 'index.html')) || (url === '/' && existsSync('dist/index.html'));

const problems = [];
const hugoRows = map.filter((m) => m.hugoUrl !== undefined).map((m) => {
	let status;
	if (!m.newFile) status = 'Not carried over';
	else if (!m.newUrl) status = 'n/a';
	else status = built(m.hugoUrl) ? 'Same URL, built' : 'MISSING at old URL';
	if (status === 'MISSING at old URL') problems.push(m.hugoUrl);
	return `| \`${esc(m.hugoUrl)}\` | ${m.newFile ? `\`${esc(m.newFile)}\`` : '–'} | ${status} | ${esc(m.notes || '')} |`;
});
for (const p of pages) if (p.source === 'hugo' && p.hugoPath && !built(p.hugoPath)) problems.push(p.hugoPath);
const images = map.filter((m) => m.hugoUrl === undefined);

const counts = pages.reduce((c, p) => ((c[p.source || 'unset'] = (c[p.source || 'unset'] || 0) + 1), c), {});
const out = [
	'# Content review',
	'',
	'Generated by `npm run review` from page frontmatter and `migration/hugo-map.json`. Do not edit by hand.',
	'',
	'Every page carries `source:` in its frontmatter:',
	'',
	'- **amy**: proposed by Amy Andrews in her 2025 Astro redesign (titles, descriptions, homepage hero and cards, navigation).',
	'- **hugo**: carried over verbatim from the previous Hugo/Docsy amybo.org (only markup converted).',
	'- **new**: written for this launch.',
	'',
	'`provenance:` explains pages that mix sources. To see exactly what changed on a Hugo page, compare it with the Hugo original in git history of [amy-bo/pages](https://github.com/amy-bo/pages).',
	'',
	`Totals: ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(', ')}.`,
	'',
	'## Pages',
	'',
	'| URL | Title | Source | Old Hugo URL | Notes |',
	'| --- | --- | --- | --- | --- |',
	...pages.map((p) => `| [\`${esc(p.url)}\`](${p.url}) | ${esc(p.title)} | ${p.source || '**unset**'} | ${p.hugoPath ? `\`${esc(p.hugoPath)}\`` : '–'} | ${esc(p.provenance)} |`),
	'',
	'## Every old Hugo page and its counterpart',
	'',
	problems.length ? `**${problems.length} problem(s):** ${problems.join(', ')}` : 'All old Hugo URLs resolve on the new site.',
	'',
	'| Old Hugo URL | New file | Status | Notes |',
	'| --- | --- | --- | --- |',
	...hugoRows,
	'',
	'Old URLs with no page of their own (search, tags, categories, RSS) redirect via `public/_redirects`.',
	'',
	'## Hugo images',
	'',
	'| Hugo file | New file | Notes |',
	'| --- | --- | --- |',
	...images.map((m) => `| \`${esc(m.hugoFile)}\` | ${m.newFile ? `\`${esc(m.newFile)}\`` : 'not carried over'} | ${esc(m.notes || '')} |`),
	'',
	'## Known follow-ups for reviewers',
	'',
	'- The About page’s paragraph about the Docsy porridge photo was removed, because the photo is not used on this site.',
	'- `electroPioreactor v0.02` has the Hugo title "electroPioreactor v0.02.md" (a typo carried over verbatim).',
	'- The Legal screenshot `Xnip2023-07-06_16-30-59.png` was unreferenced on the Hugo site; it is kept for parity.',
	'',
];
writeFileSync('REVIEW.md', out.join('\n'));
console.log(`REVIEW.md written: ${pages.length} pages, ${hugoRows.length} Hugo pages, ${problems.length} problem(s).`);
if (problems.length) process.exit(1);
